version: '3.4'

services:
  booking.web:
    image: ${DOCKER_REGISTRY-}bookingweb
    build:
      context: .
      dockerfile: Booking.Web/Dockerfile
  booking.sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Booking.Sql